### ISSUE TITLE
Create with Proxy should be updated to pass proxy to TokenCredential.

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-snippets-dotnet#12]
https://github.com/microsoftgraph/msgraph-snippets-dotnet/blob/9eea7c798a62179d7fd7bcbf23e0b6d7eac822dd/src/SdkSnippets/Snippets/CustomClients.cs#L57

```cs
        // URI to proxy
        var proxyAddress = "http://localhost:8888";
        // Create a new System.Net.Http.HttpClientHandler with the proxy
        var handler = new HttpClientHandler
        {
            // Create a new System.Net.WebProxy
            // See WebProxy documentation for scenarios requiring
            // authentication to the proxy
            Proxy = new WebProxy(new Uri(proxyAddress))
        };
        // Create an options object for the credential being used
        // For example, here we're using a ClientSecretCredential so
        // we create a ClientSecretCredentialOptions object
        var options = new ClientSecretCredentialOptions
        {
            // Create a new Azure.Core.HttpClientTransport
            Transport = new HttpClientTransport(handler)
        };
        var credential = new ClientSecretCredential(
            "YOUR_TENANT_ID",
            "YOUR_CLIENT_ID",
            "YOUR_CLIENT_SECRET",
            options
        );
        var scopes = new[] { "https://graph.microsoft.com/.default" };
        // This example works with Microsoft.Graph 5+
        var httpClient = GraphClientFactory.Create(proxy: new WebProxy(new Uri(proxyAddress)));

        var graphClient = new GraphServiceClient(httpClient, new AzureIdentityAuthenticationProvider(credential, scopes: scopes));
```

**Comment by jasonjoh** [comment]
Interesting. Isn't this sort of out of scope for Graph? What happens when Azure.Identity changes how there classes interact with proxies? ;)

How about instead I add a comment to the snippet that if token requests need to go through proxy then it has to be configured separately? Maybe with a link to https://learn.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.transport?view=azure-dotnet#azure-core-clientoptions-transport?

**Comment by andrueastman** [comment]
>  Isn't this sort of out of scope for Graph? What happens when Azure.Identity changes how there classes interact with proxies? ;)

I agree @jasonjoh. This is valid.

> How about instead I add a comment to the snippet that if token requests need to go through proxy then it has to be configured separately? Maybe with a link to https://learn.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.transport?view=azure-dotnet#azure-core-clientoptions-transport?

This works for me as well. In my head a user may be unaware that the token requests also need to pass through the proxy, so this would be helpful in helping someone realize that.
